### PR TITLE
Cleaned up the project

### PR DESCRIPTION
**Pull request by przemykomo**
- Moved definitions to .cpp files (please learn c++)
- Moved to CMake
- Moved to glad (Opengl function loader)
- Added information to README.md how to clone with submodules and build with cmake
- Moved assets to assets folder

### CODE REVIEW

**Comment by warriormaster12** [comment]
isn't glad a library that is meant for windows?

**Comment by przemykomo** [comment]
No, I use it on linux without problems.

**Comment by warriormaster12** [comment]
Got it. 

Quick question, what is motivating you to commit to this project?

**Comment by przemykomo** [comment]
If I can have some time and can help, why not?

**Comment by warriormaster12** [comment]
I was just surprised that someone wanted to contribute :D

**Comment by warriormaster12** [comment]
@przemykomo hey, could you help me with one problem? 

On my ubuntu based distro I can compile the game just fine but on Arch I get this error 

`/usr/bin/ld: CMakeFiles/OpenGlEngine.dir/src/glad.c.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/OpenGlEngine.dir/build.make:184: OpenGlEngine] Error 1
make[1]: *** [CMakeFiles/Makefile2:311: CMakeFiles/OpenGlEngine.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
`

**Comment by przemykomo** [comment]
I just noticed this comment, sorry I do not read my email very often and notifications don't work here.
You need to add 
```cmake
target_link_libraries(OpenGlEngine PRIVATE ${CMAKE_DL_LIBS})
```
to CMakeLists.txt, so it would see `dlclose` function in glad.c

**Comment by warriormaster12** [comment]
No problem, thanks for the tip :D 
I'll try it out as soon as I can

**Pull request merged**
